export const ROUTERS = {
  LOGIN: '/login',
  LOGOUT: '/logout',
  HOME: '/',
  BOOKING: '/booking',
  PRICE: '/price',
  CUSTOMER: '/participant/customer',
  SUPPLIER: '/participant/supplier',
  DEPOT: '/master-data/depot',
  DEPOT_EDIT: (depotId: string) => `/master-data/depot/edit/${depotId}`,
  LOCATION: '/master-data/location',
  TYPES_OF_CONTAINER: '/master-data/type-of-container',
  TYPES_OF_EXPENSES: '/master-data/types-of-expenses',
  UNIT_OF_MEASUREMENT: '/master-data/unit-of-measurement',
  CURRENCY: '/master-data/currency',
};
