export const ROUTERS = {
  LOGIN: '/login',
  LOGOUT: '/logout',
  HOME: '/',
  CONTAINER: '/container',
  BOOKING: '/booking',
  PRICE: '/price',
  CUSTOMER: '/customer',
  SUPPLIER: '/supplier',
  DEPOT: '/depot',
  DEPOT_EDIT: (depotId: string) => `/depot/edit/${depotId}`,
  LOCATION: '/location',
  COST_TYPE: '/cost-type',
  CALCULATION_UNIT: '/calculation-unit',
  CURRENCY: '/currency',
};
