export const ROUTERS = {
  LOGIN: '/login',
  LOGOUT: '/logout',
  HOME: '/',
  BOOKING: '/booking',
  BOOKING_EDIT: (bookingId: string) => `/booking/edit/${bookingId}`,
  QUOTATION: '/quotation',
  QUOTATION_EDIT: (quotationId: string) => `/quotation/edit/${quotationId}`,
  CUSTOMER: '/partner/customer',
  CUSTOMER_EDIT: (customerId: string) => `/partner/customer/edit/${customerId}`,
  DEBTOR: '/partner/debtor',
  DEBTOR_EDIT: (debtorId: string) => `/partner/debtor/edit/${debtorId}`,
  SUPPLIER: '/partner/supplier',
  SUPPLIER_EDIT: (supplierId: string) => `/partner/supplier/edit/${supplierId}`,
  PORT: '/master-data/port',
  PORT_EDIT: (portId: string) => `/master-data/port/edit/${portId}`,
  DEPOT: '/master-data/depot',
  DEPOT_EDIT: (depotId: string) => `/master-data/depot/edit/${depotId}`,
  LOCATION: '/master-data/location',
  LOCATION_EDIT: (locationId: string) =>
    `/master-data/location/edit/${locationId}`,
  CONTAINER: '/master-data/container',
  CONTAINER_EDIT: (containerId: string) =>
    `/master-data/container/edit/${containerId}`,
  UNIT: '/master-data/unit',
  UNIT_EDIT: (unitId: string) => `/master-data/unit/edit/${unitId}`,
  EXCHANGE_RATE: '/master-data/exchange-rate',
  EXCHANGE_RATE_EDIT: (exchangeRateId: string) =>
    `/master-data/exchange-rate/edit/${exchangeRateId}`,
  CURRENCY: '/master-data/currency',
  CURRENCY_EDIT: (currencyId: string) =>
    `/master-data/currency/edit/${currencyId}`,
  BANK: '/master-data/bank',
  BANK_EDIT: (bankId: string) => `/master-data/bank/edit/${bankId}`,
  TYPE_OF_LOCATION: '/master-data/type-of-location',
  TYPE_OF_LOCATION_EDIT: (typeOfLocationId: string) =>
    `/master-data/type-of-location/edit/${typeOfLocationId}`,
  TYPES_OF_CONTAINER: '/master-data/type-of-container',
  TYPES_OF_CONTAINER_EDIT: (typeOfContainerId: string) =>
    `/master-data/type-of-container/edit/${typeOfContainerId}`,
  TYPES_OF_EXPENSES: '/master-data/type-of-expenses',
  TYPES_OF_EXPENSES_EDIT: (typeOfExpenseId: string) =>
    `/master-data/type-of-expenses/edit/${typeOfExpenseId}`,
  STAFF: '/system/staff',
  STAFF_EDIT: (staffId: string) => `/system/staff/edit/${staffId}`,
  PERMISSION: '/system/permission',
  PERMISSION_EDIT: (permissionId: string) =>
    `/system/permission/edit/${permissionId}`,
};

// export const ROUTER_TITLE = {
//   '/': 'HOME',
//   '/quotation': 'QUOTATION',
//   '/quotation/edit/[id]': 'QUOTATION_EDIT',
//   '/booking': 'BOOKING',
//   '/booking/edit/[id]': 'BOOKING_EDIT',
//   '/partner/customer': 'CUSTOMER',
//   '/partner/customer/edit/[id]': 'CUSTOMER_EDIT',
//   '/partner/supplier': 'SUPPLIER',
//   '/partner/supplier/edit/[id]': 'SUPPLIER_EDIT',
//   '/master-data/port': 'PORT',
//   '/master-data/port/edit/[id]': 'PORT_EDIT',
//   '/master-data/location': 'LOCATION',
//   '/master-data/location/edit/[id]': 'LOCATION_EDIT',
//   '/master-data/type-of-expenses': 'TYPES_OF_EXPENSES',
//   '/master-data/type-of-expenses/edit/[id]': 'TYPES_OF_EXPENSES_EDIT',
//   '/master-data/type-of-container': 'TYPES_OF_CONTAINER',
//   '/master-data/type-of-container/edit/[id]': 'TYPE_OF_LOCATION_EDIT',
//   '/master-data/type-of-location': 'TYPE_OF_LOCATION',
//   '/master-data/type-of-location/edit/[id]': 'TYPE_OF_LOCATION_EDIT',
//   '/master-data/unit': 'UNIT',
//   '/master-data/unit/edit/[id]': 'UNIT_EDIT',
//   '/master-data/currency': 'CURRENCY',
//   '/master-data/currency/edit/[id]': 'CURRENCY_EDIT',
//   '/system/staff': 'STAFF',
//   '/system/staff/edit/[id]': 'STAFF_EDIT',
//   '/system/permission': 'PERMISSION',
//   '/system/permission/edit/[id]': 'PERMISSION_EDIT',
//   '/404': 'ERROR',
// };
